/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutButton: typeof import('./src/components/FloatingButtons/AboutButton.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    AvoidGapsSwitch: typeof import('./src/components/AppBar/TimetableSettings/AvoidGapsSwitch.vue')['default']
    BuildTimetableButton: typeof import('./src/components/AppBar/TimetableSettings/BuildTimetableButton.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ChangeTheme: typeof import('./src/components/AppBar/ChangeTheme.vue')['default']
    CourseDetailCardsLayer: typeof import('./src/components/CourseDetails/CourseDetailCardsLayer.vue')['default']
    CourseDetailsPopup: typeof import('./src/components/CourseDetails/CourseDetailsPopup.vue')['default']
    CourseEnrolmentControls: typeof import('./src/components/CourseDetails/CourseEnrolmentControls.vue')['default']
    CourseSearchBar: typeof import('./src/components/AppBar/CourseSearchBar.vue')['default']
    CourseSectionPicker: typeof import('./src/components/Popup/CourseSectionPicker.vue')['default']
    CourseTimetable: typeof import('./src/components/CourseDetails/CourseTimetable.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DivisionalLegend: typeof import('./src/components/CourseDetails/DivisionalLegend.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EnrolmentLegendPopup: typeof import('./src/components/CourseDetails/EnrolmentLegendPopup.vue')['default']
    ExportCalendarButton: typeof import('./src/components/FloatingButtons/ExportCalendarButton.vue')['default']
    ExportToJsonButton: typeof import('./src/components/FloatingButtons/ExportToJsonButton.vue')['default']
    ExportToPngButton: typeof import('./src/components/FloatingButtons/ExportToPngButton.vue')['default']
    HelpDial: typeof import('./src/components/FloatingButtons/HelpDial.vue')['default']
    HourSwitch: typeof import('./src/components/Timetable/HourSwitch.vue')['default']
    ImportButton: typeof import('./src/components/FloatingButtons/ImportButton.vue')['default']
    IncludeUnavailableSwitch: typeof import('./src/components/AppBar/TimetableSettings/IncludeUnavailableSwitch.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MaxHoursInput: typeof import('./src/components/AppBar/TimetableSettings/MaxHoursInput.vue')['default']
    MiscSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/MiscSettingsGroup.vue')['default']
    NoTimetablePopup: typeof import('./src/components/Popup/NoTimetablePopup.vue')['default']
    OnlinePreferenceSelect: typeof import('./src/components/AppBar/TimetableSettings/OnlinePreferenceSelect.vue')['default']
    OverwriteLockedSectionPopup: typeof import('./src/components/Popup/OverwriteLockedSectionPopup.vue')['default']
    PreferDayOffSwitch: typeof import('./src/components/AppBar/TimetableSettings/PreferDayOffSwitch.vue')['default']
    PrefferedGapSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/PrefferedGapSettingsGroup.vue')['default']
    PrefferedTimeSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/PrefferedTimeSettingsGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectedCourseCard: typeof import('./src/components/SidePanel/SelectedCourseCard.vue')['default']
    SelectedCoursesPanel: typeof import('./src/components/SidePanel/SelectedCoursesPanel.vue')['default']
    SessionSelect: typeof import('./src/components/AppBar/SessionSelect.vue')['default']
    ShareLinkPopup: typeof import('./src/components/Popup/ShareLinkPopup.vue')['default']
    SideBar: typeof import('./src/components/SidePanel/SideBar.vue')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    TextDivider: typeof import('./src/components/Misc/TextDivider.vue')['default']
    TimeSettingSelect: typeof import('./src/components/AppBar/TimetableSettings/TimeSettingSelect.vue')['default']
    Timetable: typeof import('./src/components/Timetable/Timetable.vue')['default']
    TimetableCourseCard: typeof import('./src/components/Timetable/TimetableCourseCard.vue')['default']
    TimetableEvent: typeof import('./src/components/Timetable/TimetableEvent.vue')['default']
    TimetableSettingsMenu: typeof import('./src/components/AppBar/TimetableSettings/TimetableSettingsMenu.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TutorialButton: typeof import('./src/components/FloatingButtons/TutorialButton.vue')['default']
    TutorialPopup: typeof import('./src/components/Popup/TutorialPopup.vue')['default']
    UrlButton: typeof import('./src/components/FloatingButtons/UrlButton.vue')['default']
    Warning: typeof import('./src/components/SidePanel/Warning.vue')['default']
    WeekdaySwitch: typeof import('./src/components/Timetable/WeekdaySwitch.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
